version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: resto-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=resto_erp_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
